/**
 * PDF Report Generator
 * Creates professional PDF reports for tithe records
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TitheRecordB, TransactionLogEntry, MemberDatabase } from '@/types';
import { calculateAssemblyAnalytics, getMonthlyTitheSummary, MemberTithingPattern } from '@/services/analyticsCalculator';

// Extend jsPDF with autoTable
declare module 'jspdf' {
    interface jsPDF {
        lastAutoTable: {
            finalY: number;
        };
    }
}

const TAC_GREEN: [number, number, number] = [0, 100, 0];  // TAC brand green
// const HEADER_GRAY: [number, number, number] = [240, 240, 240];

/**
 * Common PDF header with TAC branding
 */
const addHeader = (doc: jsPDF, title: string, subtitle?: string): void => {
    // Header background
    doc.setFillColor(...TAC_GREEN);
    doc.rect(0, 0, doc.internal.pageSize.getWidth(), 35, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('THE APOSTOLIC CHURCH GHANA', doc.internal.pageSize.getWidth() / 2, 15, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(title, doc.internal.pageSize.getWidth() / 2, 25, { align: 'center' });

    if (subtitle) {
        doc.setFontSize(10);
        doc.text(subtitle, doc.internal.pageSize.getWidth() / 2, 32, { align: 'center' });
    }

    // Reset text color
    doc.setTextColor(0, 0, 0);
};

/**
 * Common PDF footer with page numbers
 */
const addFooter = (doc: jsPDF): void => {
    const pageCount = doc.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);

        const text = `Page ${i} of ${pageCount} | Generated by TACTMS on ${new Date().toLocaleDateString()}`;
        doc.text(text, doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
    }
};

/**
 * Generate Weekly Tithe Summary PDF
 */
export const generateWeeklySummaryPDF = (
    titheList: TitheRecordB[],
    assemblyName: string,
    date: string
): jsPDF => {
    const doc = new jsPDF('p', 'mm', 'a4');

    addHeader(doc, 'WEEKLY TITHE SUMMARY', `${assemblyName} Assembly | ${date}`);

    // Summary stats
    const totalAmount = titheList.reduce((sum, r) => sum + (Number(r["Transaction Amount"]) || 0), 0);
    const tithersCount = titheList.filter(r => (Number(r["Transaction Amount"]) || 0) > 0).length;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Tithe: GHS ${totalAmount.toLocaleString()}`, 14, 50);
    doc.text(`Number of Tithers: ${tithersCount}`, 14, 57);

    // Tithe list table
    const tableData = titheList
        .filter(r => (Number(r["Transaction Amount"]) || 0) > 0)
        .map((r, i) => [
            i + 1,
            r["Membership Number"].replace(/\s*\([^)]*\)/, ''), // Remove ID part for brevity
            `GHS ${Number(r["Transaction Amount"]).toLocaleString()}`
        ]);

    autoTable(doc, {
        startY: 65,
        head: [['#', 'Member Name', 'Amount']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: TAC_GREEN, textColor: [255, 255, 255] },
        columnStyles: {
            0: { cellWidth: 15 },
            1: { cellWidth: 'auto' },
            2: { cellWidth: 40, halign: 'right' }
        },
        styles: { fontSize: 9 },
    });

    addFooter(doc);
    return doc;
};

/**
 * Generate Monthly Summary PDF
 */
export const generateMonthlySummaryPDF = (
    logs: TransactionLogEntry[],
    assemblyName: string,
    month: string,
    year: number
): jsPDF => {
    const doc = new jsPDF('p', 'mm', 'a4');

    addHeader(doc, 'MONTHLY TITHE SUMMARY', `${assemblyName} Assembly | ${month} ${year}`);

    // Filter logs for this month
    const monthIndex = new Date(`${month} 1, ${year}`).getMonth();
    const monthLogs = logs.filter(log => {
        const date = new Date(log.selectedDate);
        return log.assemblyName === assemblyName &&
            date.getMonth() === monthIndex &&
            date.getFullYear() === year;
    });

    const totalAmount = monthLogs.reduce((sum, log) => sum + log.totalTitheAmount, 0);
    const weeklyTotals = monthLogs.map(log => ({
        date: new Date(log.selectedDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' }),
        amount: log.totalTitheAmount,
        tithers: log.titheListData.filter(r => (Number(r["Transaction Amount"]) || 0) > 0).length
    }));

    // Summary
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Monthly Total: GHS ${totalAmount.toLocaleString()}`, 14, 50);
    doc.text(`Weeks Recorded: ${weeklyTotals.length}`, 14, 58);

    // Weekly breakdown table
    autoTable(doc, {
        startY: 68,
        head: [['Date', 'Amount', 'Tithers']],
        body: weeklyTotals.map(w => [w.date, `GHS ${w.amount.toLocaleString()}`, w.tithers]),
        theme: 'grid',
        headStyles: { fillColor: TAC_GREEN },
        columnStyles: {
            0: { cellWidth: 50 },
            1: { cellWidth: 60, halign: 'right' },
            2: { cellWidth: 40, halign: 'center' }
        },
    });

    addFooter(doc);
    return doc;
};

/**
 * Generate Member Statement PDF
 */
export const generateMemberStatementPDF = (
    memberName: string,
    memberId: string,
    logs: TransactionLogEntry[],
    year: number
): jsPDF => {
    const doc = new jsPDF('p', 'mm', 'a4');

    addHeader(doc, 'MEMBER TITHE STATEMENT', `For the Year ${year}`);

    // Member info
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Member: ${memberName}`, 14, 50);
    doc.text(`Membership No: ${memberId}`, 14, 57);

    // Collect all tithes for this member
    const memberTithes: Array<{ date: string; amount: number; assembly: string }> = [];

    for (const log of logs) {
        const yearMatch = new Date(log.selectedDate).getFullYear() === year;
        if (!yearMatch) continue;

        for (const record of log.titheListData) {
            const recordMemberId = record["Membership Number"];
            if (recordMemberId.includes(memberId)) {
                const amount = Number(record["Transaction Amount"]) || 0;
                if (amount > 0) {
                    memberTithes.push({
                        date: record["Transaction Date ('DD-MMM-YYYY')"],
                        amount,
                        assembly: log.assemblyName
                    });
                }
            }
        }
    }

    const totalYTD = memberTithes.reduce((sum, t) => sum + t.amount, 0);
    doc.text(`Total Tithe YTD: GHS ${totalYTD.toLocaleString()}`, 14, 64);

    // Tithe history table
    autoTable(doc, {
        startY: 74,
        head: [['Date', 'Amount', 'Assembly']],
        body: memberTithes.map(t => [t.date, `GHS ${t.amount.toLocaleString()}`, t.assembly]),
        theme: 'striped',
        headStyles: { fillColor: TAC_GREEN },
    });

    addFooter(doc);
    return doc;
};

/**
 * Generate Annual Report PDF with charts
 */
export const generateAnnualReportPDF = (
    logs: TransactionLogEntry[],
    memberDatabase: MemberDatabase,
    year: number,
    assemblyName?: string
): jsPDF => {
    const doc = new jsPDF('p', 'mm', 'a4');
    // const pageWidth = doc.internal.pageSize.getWidth();

    const title = assemblyName
        ? `${assemblyName} Assembly - Annual Tithe Report`
        : 'District Annual Tithe Report';

    addHeader(doc, title, `Year ${year}`);

    // Filter logs by year and optionally assembly
    const yearLogs = logs.filter(log => {
        const logYear = new Date(log.selectedDate).getFullYear();
        return logYear === year && (!assemblyName || log.assemblyName === assemblyName);
    });

    // Summary stats
    const totalYTD = yearLogs.reduce((sum, log) => sum + log.totalTitheAmount, 0);
    const weeksRecorded = yearLogs.length;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Executive Summary', 14, 50);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Tithe Collected: GHS ${totalYTD.toLocaleString()}`, 14, 60);
    doc.text(`Weeks Recorded: ${weeksRecorded}`, 14, 67);
    doc.text(`Average Weekly: GHS ${(totalYTD / Math.max(weeksRecorded, 1)).toLocaleString()}`, 14, 74);

    // Monthly breakdown
    const monthlyData = getMonthlyTitheSummary(logs, year, assemblyName);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Monthly Breakdown', 14, 90);

    autoTable(doc, {
        startY: 95,
        head: [['Month', 'Total', 'Tithers']],
        body: monthlyData.map((m: { month: string; total: number; tithersCount: number }) => [m.month, `GHS ${m.total.toLocaleString()}`, m.tithersCount]),
        theme: 'grid',
        headStyles: { fillColor: TAC_GREEN },
        columnStyles: {
            0: { cellWidth: 50 },
            1: { cellWidth: 60, halign: 'right' },
            2: { cellWidth: 40, halign: 'center' }
        },
    });

    // Add new page for top tithers if available
    if (assemblyName && yearLogs.length > 0) {
        doc.addPage();
        addHeader(doc, 'Top Tithers', `${assemblyName} Assembly - ${year}`);

        const analytics = calculateAssemblyAnalytics(yearLogs, memberDatabase, assemblyName);

        autoTable(doc, {
            startY: 50,
            head: [['Rank', 'Member', 'Total YTD', 'Weeks', 'Consistency']],
            body: analytics.topTithers.slice(0, 15).map((t: MemberTithingPattern, i: number) => [
                i + 1,
                t.memberName.replace(/\s*\([^)]*\)/, ''),
                `GHS ${t.totalTitheYTD.toLocaleString()}`,
                t.weeksPaid,
                `${t.consistencyScore}%`
            ]),
            theme: 'striped',
            headStyles: { fillColor: TAC_GREEN },
        });
    }

    addFooter(doc);
    return doc;
};

/**
 * Download a generated PDF
 */
export const downloadPDF = (doc: jsPDF, filename: string): void => {
    doc.save(`${filename}.pdf`);
};

/**
 * Open PDF in new tab for preview
 */
export const previewPDF = (doc: jsPDF): void => {
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
};
